---
title: 'Data recoding '
author: Wesnahika
date: '2022-02-23'
slug: data-recoding
categories: []
tags:
  - data
  - data-science
  - dataframe
  - r
  - GGPLOT2
---
# Recoding data 

## case study: Religion and income 

```{r}
library(tidyverse)

url <- 'https://raw.githubusercontent.com/Wesnahika/tidyverse/main/relig-income.csv'
rel_inc <- read_csv(url)
```

### Rename the columns 

```{r}
rel_inc %>%
  rename( 
    religion = `Religious tradition`, 
    n = `Sample Size` 
  )
```

### Pivot longer 

```{r}
rel_inc %>%
  rename(
    religion = `Religious tradition`,
    n = `Sample Size`
  ) %>%
  pivot_longer( 
    cols = -c(religion, n),   # all but religion and n 
    names_to = "income",  
    values_to = "proportion" 
  )
```

### Calculate the frequencies 

```{r}
rel_inc %>%
  rename(
    religion = `Religious tradition`,
    n = `Sample Size`
  ) %>%
  pivot_longer(
    cols = -c(religion, n), 
    names_to = "income", 
    values_to = "proportion"
  )

```

### save data 

```{r}

rel_inc_long <- rel_inc %>% 
  rename(
    religion = `Religious tradition`,
    n = `Sample Size`) %>%
  pivot_longer(
    cols = -c(religion, n), 
    names_to = "income", 
    values_to = "proportion")
  
```

## barplot

```{r}
ggplot(rel_inc_long, aes(y = religion, x = proportion)) +
  geom_col()

```

## Recode religion

```{r}
rel_inc_long <- rel_inc_long %>%
  mutate(religion = case_when(
    religion == "Evangelical Protestant"           ~ "Ev. Protestant",
    religion == "Historically Black Protestant"    ~ "Hist. Black Protestant",
    religion == 'Unaffiliated (religious "nones")' ~ "Unaffiliated",
    TRUE                                           ~ religion
  ))

```

## Reverse religion order

```{r}
rel_inc_long <- rel_inc_long %>%
  mutate(religion = fct_rev(religion))
```

## Add income 

```{r}
ggplot(rel_inc_long, aes(y = religion, x = proportion, fill = income)) + 
  geom_col()
```

## Fill bars 

```{r}
ggplot(rel_inc_long, aes(y = religion, x = proportion, fill = income)) +
  geom_col(position = "fill")
```

## Change colors 

```{r}
ggplot(rel_inc_long, aes(y = religion, x = proportion, fill = income)) +
  geom_col(position = "fill") +
  scale_fill_viridis_d()
```

## Change theme 

```{r}
ggplot(rel_inc_long, aes(y = religion, x = proportion, fill = income)) +
  geom_col(position = "fill") +
  scale_fill_viridis_d() +
  theme_minimal()
```

## Move legend to the bottom 

```{r}
ggplot(rel_inc_long, aes(y = religion, x = proportion, fill = income)) +
  geom_col(position = "fill") +
  scale_fill_viridis_d() +
  theme_minimal() +
  theme(legend.position = "bottom")
```

## Legend adjustments 

```{r}
ggplot(rel_inc_long, aes(y = religion, x = proportion, fill = income)) +
  geom_col(position = "fill") +
  scale_fill_viridis_d() +
  theme_minimal() +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(nrow = 2, byrow = TRUE))
```

## fix labels 

```{r}
ggplot(rel_inc_long, aes(y = religion, x = proportion, fill = income)) +
  geom_col(position = "fill") +
  scale_fill_viridis_d() +
  theme_minimal() +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(nrow = 2, byrow = TRUE)) +
  labs(
    x = "Proportion", y = "", 
    title = "Income distribution by religious group", 
    subtitle = "Source: Pew Research Center, Religious Landscape Study", 
    fill = "Income" 
    )
```

